#!/bin/bash

echo "START VPL_EXECUTION"

### load environment
ENVDIR=$HOME
if [ "$ONLINE" = "0" ] ; then ENVDIR=$RUNDIR ; fi
[ ! -f $ENVDIR/env.sh ] && echo "⚠ File \"env.sh\" missing!" && exit 0
source $ENVDIR/env.sh
[ -z "$RUNDIR" ] && echo "⚠ RUNDIR variable is not defined!" && exit 0
source $RUNDIR/vplmodel/toolkit.sh
CHECKENV
EXPORTENV

### run
cd $RUNDIR  # set current working directory
BASEDIR="$RUNDIR/download/$EXO"
[ ! -f $BASEDIR/run.sh ] && echo "⚠ File \"run.sh\" missing!" && exit 0
source $BASEDIR/run.sh

# EOF
