FROM debian:latest
MAINTAINER Aurelien Esnard <aurelien.esnard@u-bordeaux.fr>
RUN apt-get update
RUN apt-get install -y gcc
RUN apt-get install -y python3 python3-pip
# RUN pip3 install ...
WORKDIR /home/docker
